export type ITechStack = ITech[]

export type ITech =
    | "HTML"
    | "CSS"
    | "SASS"
    | "Tailwind CSS"
    | "JavaScript"
    | "TypeScript"
    | "React"
    | "Redux"
    | "Axios"
    | "Auth0"
    | "Node.js"
    | "Express.js"
    | "MongoDB"
    | "GraphQL"
    | "Python"
    | "cypress"
    | "Jest"
    | "Docker"
    | "AWS"
    | "Firebase"
    | "Testing Lib."